### ISSUE TITLE
[Bug] Wrong assignment of shutter steps with command "set shutter"

### ISSUE THREAD

**Issue by NicoHarke-BMT** [bitfocus/companion-module-sony-visca#39]
Hi all,

i use a Sony SRG-X400 BC and tried the "Set Shutter" Command in the "Sony Visca Module".
The labels of the dropdown-list don't match with what they recall at the camera.

Also some possible shutter-settings are not possible to take with the dropdown-presets.

e.g. taking "1/125  1/120" preset of the dropdownlist, sets the shutter to "1/3"

Needed commands to check if it is a problem of the camera or the module can be found at Page 34 of the Sony PDF:
https://pro.sony/support/res/manuals/E042/3230148ee903c204b912cca5c2c3f5aa/E0421001M.pdf

I use Companion Version 2.41, but also tried with 3.0.0 and 3.1.0.

**Comment by goseid** [comment]
Hello,

I'm planning to take this on right after upgrading the module to work natively with Companion 3.x.

I believe the module was originally written from the documentation from one Sony PTZ camera and there are many models with different values associated to the various settings. It will require a more complex config but should be pretty straightforward to implement these values correctly.

-Greg

**Comment by NicoHarke-BMT** [comment]
Hi Greg,
thanks for your respond.
As I saw you did the update to 3.x already, thanks for that- now i can try myself a bit as a programmer in the visca module.

I had a look at the Blackmagic ATEM module to see how the "model problem" is solved there. The module uses a "models" file in which every possible switcher (for the visca-module it would be for every cameratype) is listed and where it is said which functionality is given to that model. I think this would be a great solution for the visca module.

So first in the Config tab there has to be a dropdown of supportet modules, second there have to be all the possible presets for the different cameratypes and third there has to be a module list where is defined which camera uses which preset.

Would that be a plan you do agree to? Could i help you with anything? I think i am not good enough to do all the reprogramming by my own but would love to support if needed (e.g. copying all the different sony visca command values to a preset list, or comparing what camera uses what values)....

TIA!

Nico

**Comment by goseid** [comment]
Hi Nico,

Thanks for offering to help. What you suggest is pretty much what I was thinking as well and your help is welcome. Please go ahead and update the config file with all the necessary data. I'll add the logic in the module to pull the right data per model.

So far this module hasn't discriminated as to what features are available on certain cameras. Eventually we'll want to get that added as well.

The camera I have the most access to is the Sony SRG-X120. I test with that so if it is implemented my testing will be easier. I believe that is the same documentation as your SRG-X400 BC with slightly different features implemented. I've been trying to keep in mind all the models that people have requested feature for in here.

FYI, the canon-ptz module is also a great one to look to for inspiration. They have implemented so much of the functionality of the various models in very user friendly ways.

Thanks for your help. Let me know how it goes and if there is anything you need from me.

-Greg

**Comment by NicoHarke-BMT** [comment]
Hi Greg,

i started to make an excel chart with all the features of the different sony ptz cameras and the viscaip-commands belonging to them, to have a better overview which camera uses what command and value. For now i have added 6 PTZ models (BRC X400, SRG X400, SRG X120, BRC X1000, BRC H800, BRC H780). So i am ready to start to feed a file ;-)

Is you recommended i had a look at the canon ptz module and as you say this seems pretty much the way that should work good. Should i wait for you to implement the file structure of a "models" file, or can i just copy that one from the canon module, change it to what we need for the sony cameras and you implement that to the rest of the files?

Just tell me, how i can help best- i saw you are working hard on updating the module with updates almost every day.

KR.

**Comment by goseid** [comment]
Regarding copying the canon I'd prefer to make small adjustments to the file we have for Sony and where we need to figure something out use it as a reference.

Would you prefer to make the changes to the models file or share your chart and have me make them? I'm fine either way.

**Comment by NicoHarke-BMT** [comment]
I hope the chart is not too comlicated to understand- here you have access to it:
https://e.pcloud.link/publink/show?code=XZ3JaSZX5xWjj1KU8RU2LcLC2Psa7iWjMJX

My suggestion would be, that you make a models file with an example model in it and i can add all the other models by copy and paste. Same with the actions file- if the action file is finished in your eyes, i think i can help you out by adding actions via copy and paste to add new features for different models.

If it is easier for you to do all the work on your own this is even fine for me- i'm new to the programming thing on github so sometimes it will take more time to have it done by me than to do it on your own ;-)

**Comment by tonypiper** [comment]
Hello there. I've just submitted PR #48 to enable TCP protocol support. I was previously using the [PTZOptics VISCA module](https://github.com/bitfocus/companion-module-ptzoptics-visca), but it's very out of date, will need a lot of work to be compatible with Companion v3 and has fewer features. My VISCA-compatible clone cameras only have TCP, not UDP, so this PR will let me use this module instead. 

As well as the different commands/choices mentioned above, it might be good to have some way to specify what actions are available on a model. Perhaps we could implement ActionIds (like many other Companion modules do) and use those as a crude feature flag to determine what actions are available... Happy to get stuck in!

**Comment by goseid** [comment]
In general I'm of the opinion that the most specific module should be the best module for any device. If someone else doesn't get to it before I do, I hope to update the ptzoptics-visca module with a lot of the features that we've added to the sony-visca module recently and more. I'm excited about the TCP nature of the PTZOptics cameras because we can get data back from multiple cameras a lot easier that we can with Sony and the way the return responses to UDP.

The Sony docs that I have seen have all spec'd the UDP protocol and that is what they use with all the cameras I have come across. That is another reason I am personally a little reluctant to add TCP support to the sony-visca module.

**Comment by tonypiper** [comment]
Makes total sense. I guess there are three key aspects to consider when thinking about Companion modules for PTZ cameras

- Control protocol (VISCA, over UDP, TCP or serial)
- Camera manufacturers (Sony vs PTZOptics)
- Specific camera models 

I've not done an exhaustive search and comparison (but I have looked at all the VISCA companion modules), but it makes sense that a camera that claims to be VISCA-capable should implement a given feature using exactly the same VISCA commands. Otherwise they wouldn't be VISCA-capable.

The only thing that would vary between camera models and manufacturers is the availability of features (some have more features than others), and some parameters (zoom capability, shutter speed range etc). 

As @NicoHarke-BMT says, this is like the Blackmagic ATEMs. They all speak the same protocol but have different features and (sometimes) parameters. Building on that idea, the only difference would be as if other companies made ATEMs that were also compatible with the ATEM protocol (which they never would, but that's not the case with PTZ manufacturers).

A single well-crafted VISCA module that has a solid implementation of the VISCA protocol (over UDP, TCP and possibly Serial) but also allows the Companion user to choose between different feature sets and parameters for different cameras and manufacturers (Sony, PTZOptics and any others) would enable everyone to leverage the great work you've done on implementing features on this module, and inspire them to contribute to the 'model library' if needed.

In turn, that would enable us to get rid of 3 other VISCA Companion modules (possibly 4), none of which have been updated to work with Companion v3, and focus development efforts on just one module.

I'd be very happy to contribute to a merge like this. And I notice I feel reluctant to committing to bringing the ptzoptics-visca module up to the same level of functionality as this module, because it just feels like a duplication of effort and it's one more thing to maintain.

What do you think?

**Comment by tonypiper** [comment]
I did a bit more analysis, comparing the sony-visca, lumens, datavideo and ptzoptics modules. As best as I can tell, there are 6 (easy to implement) features implemented in the PTZOptics module that are not already in the sony-visca module. However, there are **21 PTZOptics features that are already  implemented in sony-visca but are _not_ implemented in the PTZOptics module!** Merging the two would be beneficial for PTZOptics users and save the hassle of maintaining both modules, which would benefit everyone.

**Comment by goseid** [comment]
There are definitely benefits and I expect downsides. As we implement more features getting feedback from the cameras, I expect it will become more and more challenging to handle the different ways they are implemented and the different real world values that the digital values represent. Difficult doesn't mean impossible though so it is worth considering.

One consideration is that once a module is out there, people implement it, rely on it, and the modules tend to live on. It would seem to have modules abandoned modules but maybe there is a way to deal with that.

I've wrestled with what the sony-visca module is a bit. Is it a protocol module that strives to fully implement the VISCA protocol as Sony has spec'd it which has been adopted and modified by many manufacturers? Is it the module for Sony cameras that use the VISCA protocol? In many ways modules for other manufacturers have a much clearer path forward. Implement the module for their models and ignore everything else.

I don't have answers, but there are some good questions. As a developer I'm relatively new to working on companion modules. I'm going to try to get some of the core developers to weigh in on this. They have a better vision for the overall direction and some of them gave this module its start.

**Comment by krocheck** [comment]
I have many thoughts and none point to one way or the other being best for user, developers, or the project.  I saw a reference to the ATEM in a prior post and how that module handles tons of different models, but what one has to understand about that implementation is that it uses a 3rd party library that handles much of the model-level functionality differences internally.  There's various calls in the companion module to check and deal with those, but the heavy lifting is not done within the Companion project/module itself.

I've done the heavy handed, multiple model support thing for both Shure and I put a major effort into merging 3 or 4 Novastar modules into a common one.  The `shure-wireless` was an original effort to do a single module that conforms to multiple Shure wireless models, and in fact its a very similar use-case to here, because the various models use a relatively common instruction set, but vary the values and/or the instructions slightly.  There's a ton of nuance and finesse in the module to get 4 different models to report and behave exactly the same but to the features they have implemented.  But what's worse is that Shure updates the model's APIs in firmware but not quite the same way and not on the same cycle.  If I were to tackle `shure-wireless` again today knowing what I know, it would in fact be 4 different modules for the 4 different models.  The juice wasn't worth the squeeze in terms of the layers of complexity to deal with those nuance model differences and matrix of instruction support.

Because of my experience dealing with complexity of matrixing different modes/support within a single module, I actually investigated merging all the VISCA modules back in 2019, and I determined back then that the matrixing of manufacturer and model would become exceedingly complex given the vast and extremely varied use of the standard, to a point that it would become detrimental.  You can disagree with my use of 'vast and extremely varied' but when you look at the details of the implementations all the way down to the subtle module differences just within a make, they start to add up quickly.  What I mean is that as you need to layer more and more complexity for instruction support, range support within instructions, it becomes increasingly easy to accidentally break a make/model without knowing it.  And with VISCA, there's various developers doing fresh implementation of makes and others contributing to existing makes that I simply expect with a single massive module that we would be breaking lots of things in the process of fixing other things or adding support for new models.

Its just too difficult of an industry standard IMO to go down the unified model approach, and I prefer the multiple, manufacturer-specific module approach we have now even if it creates headaches clearly outlined in this thread.

That being said, I don't know if a search for a VISCA library (similar to what we use for ATEM) has ever been done.  But if there is such a module that is actively trying to support all the makes/models and expose them as a unified API then that would be worth wrapping a module around.

**Comment by goseid** [comment]
Hi Tony,

I've wrestled with this decision and have been on both sides of it. There are definitely benefits to what you propose. In the end I think it comes down to this being the sony-visca module. If it was generic-visca I would have gladly accepted your recommendation and your pull request.

One of the things that I appreciate about the Companion community is that they are open and encouraging of ideas and contributions. I strive to follow in the examples of folks that have welcomed me and probably let me carry on with things they would not have chosen to do personally.

One of the responsibilities of helping maintain a module is to be discerning about the changes adopted. If we accept every proposal we can end up with a module that does too much, is confusing to users and difficult to maintain. I do believe your proposed changes are all positive and do not cross that line. However, it would move the line in that direction and soon we would be asked to make other changes to accommodate other devices.

Your challenge has helped me to consider more clearly what the purpose and scope of this module is. I see that as the implementation for the VISCA protocol for Sony products. I am glad that it works with other manufacturer's devices and that it is useful beyond Sony products. However, it is my opinion that this module should implement as many features as we can for Sony devices and not try to be all things to all VISCA devices.

Your code is good and your contributions would be of valuable to the Companion project. I'd encourage you to keep contributing and if you haven't already, that you join the [Bitfocus Slack](https://join.slack.com/t/bitfocusio/shared_invite/zt-o1i0mohx-p_m5I7fUEUJ1BBu_KrDN2Q) and in particular the module-development channel.

Thanks for your patience and understanding,
-Greg

**Comment by goseid** [comment]
@NicoHarke-BMT this is next on my list of things to accomplish. Thanks for your work on it and your patience.

**Comment by goseid** [comment]
The "wrong assignment of shutter steps" should be fixed in the latest release. It should be added to the latest beta build soon. Please test with your models and report back anything was missed. I've tested it pretty thoroughly on the SRG-X120s that I have access to.

Models included: 
BRC -X400, BRC-X401, SRG-X400, SRG-X402, SRG-X120, SRG-201M2, SRG-HD1M2, SRG-X40UH, SRG-H40UH, BRC-H780, BRC-H800, BRC-X1000

If your model was missed please let us know. And if you can, please point us at the VISCA documentation for it.

**Comment by gonthegeek** [comment]
Hello @goseid i'm wanting to use this module with the model ILME-FR7, here's the documentation

[VISCA-Command-List-Version-1.00.pdf](https://github.com/bitfocus/companion-module-sony-visca/files/11538601/VISCA-Command-List-Version-1.00.pdf)

**Comment by NicoHarke-BMT** [comment]
> The "wrong assignment of shutter steps" should be fixed in the latest release. It should be added to the latest beta build soon. Please test with your models and report back anything was missed. I've tested it pretty thoroughly on the SRG-X120s that I have access to.
> 
> Models included: BRC -X400, BRC-X401, SRG-X400, SRG-X402, SRG-X120, SRG-201M2, SRG-HD1M2, SRG-X40UH, SRG-H40UH, BRC-H780, BRC-H800, BRC-X1000
> 
> If your model was missed please let us know. And if you can, please point us at the VISCA documentation for it.

Hey Greg, tried to check with version 3.0.0 5896 (on an ARM Mac) and can't get the Sony Visca Module working there. It says "Crashed" right after adding the Instance.
Logfile says: "23.05.23 22:15:55 Instance/ModuleHost: Instance "VISCA" failed to init: Error: Cannot read properties of undefined (reading 'CAMERA_ID') TypeError: Cannot read properties of undefined (reading 'CAMERA_ID')
    at /Applications/Companion.app/Contents/Resources/bundled-modules/sony-visca/main.js:2:320041
    at x.getConfigFields (/Applications/Companion.app/Contents/Resources/bundled-modules/sony-visca/main.js:2:320509)
    at /Applications/Companion.app/Contents/Resources/bundled-modules/sony-visca/main.js:2:218939
    at /Applications/Companion.app/Contents/Resources/bundled-modules/sony-visca/main.js:2:189734
    at t.default._tryToStartAnother (/Applications/Companion.app/Contents/Resources/bundled-modules/sony-visca/main.js:2:188781)
    at /Applications/Companion.app/Contents/Resources/bundled-modules/sony-visca/main.js:2:189941
    at new Promise (<anonymous>)
    at t.default.add (/Applications/Companion.app/Contents/Resources/bundled-modules/sony-visca/main.js:2:189584)
    at x._handleInit (/Applications/Companion.app/Contents/Resources/bundled-modules/sony-visca/main.js:2:218773)
    at t.IpcWrapper.receivedMessage (/Applications/Companion.app/Contents/Resources/bundled-modules/sony-visca/main.js:2:203759)"

Is it a build-problem, or a bigger bug in the latest release?

Thanks a lot for all the work you've done to the module!

**Comment by goseid** [comment]
I discovered that one too. It's a regression bug when I added some features it worked with my test profile but not when creating a new instance.

I've fixed that bug and I'm wrapping up some other minor improvements before releasing a new version. We should have the updates available in the next 24 hours.

**Comment by goseid** [comment]
@NicoHarke-BMT that bug is fixed and deployed in the latest beta Companion v3.0.0+5901-beta and newer.

**Comment by NicoHarke-BMT** [comment]
@goseid hey Greg, we finally had time to check the update and i have to say it works perfectly great! Thank for all the work.

As next we tried to use the feedbacks but figuered out, that these are only companion-internal variables that are set by the module, not real visca-feedback from the camera. Should i do a feature request here on github, or are you coincidentally working on it and we can give you any help? I got a new colleague at the beginning of july and she es more familiar with programming than i am- so maybe after a little jumpstart we can solve it by our own...

KR!

Nico

**Comment by goseid** [comment]
Hi @NicoHarke-BMT 

You are correct in your observations. We could implement actual state from one camera but the VISCA protocol responds to the same companion instance for all cameras so it makes it difficult to implement for uses with multiple cameras.

The companion project is aware of it in issue [#2399](https://github.com/bitfocus/companion/issues/2399) and does plan to add some more functionality in the UDP handling for cases like this. Unfortunately for us they have higher priorities they have been working on so far. Once they have included the additional functionality it should be pretty straightforward for us to get actual state info from all cameras.

Although it is feasible to implement the request for a single instance of a camera now, I think that would lead to a bad user experience for those with multiple cameras. I haven't tackled it hoping we could offer a more complete solution soon.

I'm in a busy stretch right now where my work is very demanding. On the other hand I'll be using my Sony PTZs daily for the next 6 weeks and I want those features badly too. I may implement a back channel way of getting the state from multiple cameras rather than wait for the improved UDP implementation in the upstream project.
